name: our_journey_app
description: "A Flutter app that retells Our Journey story with Firebase backend."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.5.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  go_router: ^14.1.4
  file_picker: ^8.1.2
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

